; Generated by scripts/normalize_kick3d_for_acme.py
*=$0801
!byte $0b,$08,$0a,$00,$9e,$32,$30,$36,$31,$00,$00,$00

jmp main

viewPitch !byte 0

applyViewPitchTop
	lda viewPitch
	beq applyViewPitchTop_exit
	bpl applyViewPitchTop_down
	lda screen_DrawTop
	clc
	adc viewPitch
	bcs applyViewPitchTop_store
	lda #0
	jmp applyViewPitchTop_store
applyViewPitchTop_down
	lda screen_DrawTop
	clc
	adc viewPitch
	cmp #25
	bcc applyViewPitchTop_store
	lda #24
applyViewPitchTop_store
	sta screen_DrawTop
applyViewPitchTop_exit
	rts

applyViewPitchBottom
	lda viewPitch
	beq applyViewPitchBottom_exit
	bpl applyViewPitchBottom_down
	lda screen_DrawBottom
	clc
	adc viewPitch
	bcs applyViewPitchBottom_store
	lda #0
	jmp applyViewPitchBottom_store
applyViewPitchBottom_down
	lda screen_DrawBottom
	clc
	adc viewPitch
	cmp #50
	bcc applyViewPitchBottom_store
	lda #49
applyViewPitchBottom_store
	sta screen_DrawBottom
applyViewPitchBottom_exit
	rts

!source ".build/mapping.asm"
!source ".build/main.asm"
!source ".build/math.asm"
!source ".build/user.asm"
!source ".build/display.asm"
!source ".build/sprites.asm"
!source ".build/raycast.asm"
!source ".build/rayscan.asm"
!source ".build/interrupts.asm"
!source ".build/resources.asm"
!source ".build/tables.asm"
