; Generated by scripts/normalize_kick3d_for_acme.py
*=$0801
!byte $0b,$08,$0a,$00,$9e,$32,$30,$36,$31,$00,$00,$00

jmp main

viewPitch !byte 0

applyViewPitchTop
	lda viewPitch
	beq applyViewPitchTop_exit
	bpl applyViewPitchTop_down
	lda screen_DrawTop
	clc
	adc viewPitch
	bcs applyViewPitchTop_store
	lda #0
	jmp applyViewPitchTop_store
applyViewPitchTop_down
	lda screen_DrawTop
	clc
	adc viewPitch
	cmp #25
	bcc applyViewPitchTop_store
	lda #24
applyViewPitchTop_store
	sta screen_DrawTop
applyViewPitchTop_exit
	rts

applyViewPitchBottom
	lda viewPitch
	beq applyViewPitchBottom_exit
	bpl applyViewPitchBottom_down
	lda screen_DrawBottom
	clc
	adc viewPitch
	bcs applyViewPitchBottom_store
	lda #0
	jmp applyViewPitchBottom_store
applyViewPitchBottom_down
	lda screen_DrawBottom
	clc
	adc viewPitch
	cmp #50
	bcc applyViewPitchBottom_store
	lda #49
applyViewPitchBottom_store
	sta screen_DrawBottom
applyViewPitchBottom_exit
	rts

!set MC_GRASS = $81
!set MC_DIRT = $82
!set MC_STONE = $83
!set MC_COBBLE = $84
!set MC_LOG = $85
!set MC_LEAVES = $86
!set MC_PLANK = $87
!set MC_COALORE = $88
!set MC_IRONORE = $89
!set MC_SAND = $8a
!set MC_GLASS = $8b
!set MC_SAPLING = $8c
!set MC_TABLE = $8d
!set MC_FURNACE = $8e
!set MC_CHEST = $8f

!source ".build/mapping.asm"
!source ".build/tables.asm"
!source ".build/math.asm"
!source ".build/minecraft_user.asm"
!source ".build/display.asm"
!source ".build/sprites.asm"
!source ".build/raycast.asm"
!source ".build/rayscan.asm"
!source ".build/interrupts.asm"
!source ".build/minecraft_resources.asm"
