#!/usr/bin/env python3
from pathlib import Path
import re
import shutil


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / ".build"

BLOCKS64K_SOURCES = [
    ROOT / "Kick-3D" / "mapping.asm",
    ROOT / "Kick-3D" / "tables.asm",
    ROOT / "Kick-3D" / "math.asm",
    ROOT / "src" / "blocks64k_user.asm",
    ROOT / "Kick-3D" / "display.asm",
    ROOT / "Kick-3D" / "sprites.asm",
    ROOT / "Kick-3D" / "raycast.asm",
    ROOT / "Kick-3D" / "rayscan.asm",
    ROOT / "Kick-3D" / "interrupts.asm",
    ROOT / "src" / "blocks64k_resources.asm",
]

KICK3D_SOURCES = [
    ROOT / "Kick-3D" / "mapping.asm",
    ROOT / "Kick-3D" / "main.asm",
    ROOT / "Kick-3D" / "math.asm",
    ROOT / "Kick-3D" / "user.asm",
    ROOT / "Kick-3D" / "display.asm",
    ROOT / "Kick-3D" / "sprites.asm",
    ROOT / "Kick-3D" / "raycast.asm",
    ROOT / "Kick-3D" / "rayscan.asm",
    ROOT / "Kick-3D" / "interrupts.asm",
    ROOT / "Kick-3D" / "resources.asm",
    ROOT / "Kick-3D" / "tables.asm",
]

NAMESPACE_ZONES = {
    "screen",
    "zBuffer",
    "slopeLen",
    "scrAddr",
    "player",
    "event",
    "mc",
    "playerSprite",
    "dirSprite",
    "raySprite",
    "backSprite",
    "setInterrupt",
    "getKeyboard",
    "mapEvent",
}


NAMESPACE_REF_RE = re.compile(
    r"\b(" + "|".join(sorted(NAMESPACE_ZONES)) + r")\.([A-Za-z_][A-Za-z0-9_]*)"
)


def strip_old_build_dir() -> None:
    if BUILD.exists():
        shutil.rmtree(BUILD)
    BUILD.mkdir(parents=True)


GLOBAL_LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):?(?=\s|$)")
LOCAL_REF_RE = re.compile(r"(?<![A-Za-z0-9_])\.([A-Za-z_][A-Za-z0-9_]*)")


def normalize_line(
    line: str,
    active_namespace: str | None,
    current_scope: str,
) -> tuple[str | None, str | None, str]:
    line = line.replace("//", ";")

    zone = re.match(r"^\s*!zone\s+([A-Za-z_][A-Za-z0-9_]*):?\s*(?:;.*)?$", line)
    if zone:
        name = zone.group(1)
        if name in NAMESPACE_ZONES:
            return None, name, current_scope
        return None, None, current_scope

    if re.match(r"^\s*!basic\b", line):
        return None, active_namespace, current_scope

    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*:?\s*(?:;.*)?$", line):
        active_namespace = None

    if active_namespace:
        line = re.sub(
            r"^\s*\.([A-Za-z_][A-Za-z0-9_]*)(:?)",
            rf"{active_namespace}_\1\2",
            line,
        )
    else:
        line = re.sub(r"^\s+\.((?:scanLine|scanColor)[A-Za-z0-9_]*)(:?)", r"setInterrupt_\1\2", line)
        line = re.sub(r"^\s+\.scan\b", "getKeyboard_scan", line)

    # ACME requires labels to start in the leftmost column. C64Studio sources
    # often indent local dotted labels inside zones.
    line = re.sub(r"^\s+(\.[A-Za-z_][A-Za-z0-9_]*:?)", r"\1", line)
    line = re.sub(r'^(\s*\*=\$[0-9a-fA-F]+)\s+"[^"]+"\s*$', r"\1\n", line)
    line = NAMESPACE_REF_RE.sub(r"\1_\2", line)

    if not active_namespace:
        global_match = GLOBAL_LABEL_RE.match(line)
        if global_match and not line.startswith("!"):
            current_scope = global_match.group(1)

        if "." in line:
            line = LOCAL_REF_RE.sub(lambda m: f"{current_scope}_{m.group(1)}", line)

    line = re.sub(r"\b(?:irq1|irq2)_((?:scanLine|scanColor)[A-Za-z0-9_]*)", r"setInterrupt_\1", line)

    if "sta screen_DrawTop" in line:
        line = line.rstrip("\n") + "\n\t\t\tjsr applyViewPitchTop\n"
    elif "sta screen_DrawBottom" in line:
        line = line.rstrip("\n") + "\n\t\t\tjsr applyViewPitchBottom\n"

    return line, active_namespace, current_scope


def normalize_source(src: Path) -> Path:
    dest = BUILD / src.name
    with src.open("r", encoding="utf-8-sig", newline="") as f:
        lines = f.readlines()

    active_namespace = None
    current_scope = src.stem.replace("-", "_")
    with dest.open("w", encoding="utf-8", newline="\n") as f:
        for line in lines:
            out, active_namespace, current_scope = normalize_line(
                line,
                active_namespace,
                current_scope,
            )
            if out is not None:
                f.write(out)
    return dest


def write_entrypoint(name: str, generated: list[Path], include_blocks64k_constants: bool) -> None:
    entry = BUILD / name
    with entry.open("w", encoding="utf-8", newline="\n") as f:
        f.write("; Generated by scripts/normalize_kick3d_for_acme.py\n")
        f.write("*=$0801\n")
        # BASIC: 10 SYS 2061. The trampoline at 2061 jumps to the real main
        # routine, so included data may safely live before the main label.
        f.write("!byte $0b,$08,$0a,$00,$9e,$32,$30,$36,$31,$00,$00,$00\n\n")
        f.write("jmp main\n\n")
        f.write("viewPitch !byte 0\n\n")
        f.write("applyViewPitchTop\n")
        f.write("\tlda viewPitch\n")
        f.write("\tbeq applyViewPitchTop_exit\n")
        f.write("\tbpl applyViewPitchTop_down\n")
        f.write("\tlda screen_DrawTop\n")
        f.write("\tclc\n")
        f.write("\tadc viewPitch\n")
        f.write("\tbcs applyViewPitchTop_store\n")
        f.write("\tlda #0\n")
        f.write("\tjmp applyViewPitchTop_store\n")
        f.write("applyViewPitchTop_down\n")
        f.write("\tlda screen_DrawTop\n")
        f.write("\tclc\n")
        f.write("\tadc viewPitch\n")
        f.write("\tcmp #25\n")
        f.write("\tbcc applyViewPitchTop_store\n")
        f.write("\tlda #24\n")
        f.write("applyViewPitchTop_store\n")
        f.write("\tsta screen_DrawTop\n")
        f.write("applyViewPitchTop_exit\n")
        f.write("\trts\n\n")
        f.write("applyViewPitchBottom\n")
        f.write("\tlda viewPitch\n")
        f.write("\tbeq applyViewPitchBottom_exit\n")
        f.write("\tbpl applyViewPitchBottom_down\n")
        f.write("\tlda screen_DrawBottom\n")
        f.write("\tclc\n")
        f.write("\tadc viewPitch\n")
        f.write("\tbcs applyViewPitchBottom_store\n")
        f.write("\tlda #0\n")
        f.write("\tjmp applyViewPitchBottom_store\n")
        f.write("applyViewPitchBottom_down\n")
        f.write("\tlda screen_DrawBottom\n")
        f.write("\tclc\n")
        f.write("\tadc viewPitch\n")
        f.write("\tcmp #50\n")
        f.write("\tbcc applyViewPitchBottom_store\n")
        f.write("\tlda #49\n")
        f.write("applyViewPitchBottom_store\n")
        f.write("\tsta screen_DrawBottom\n")
        f.write("applyViewPitchBottom_exit\n")
        f.write("\trts\n\n")
        if include_blocks64k_constants:
            f.write("!set MC_GRASS = $81\n")
            f.write("!set MC_DIRT = $82\n")
            f.write("!set MC_STONE = $83\n")
            f.write("!set MC_COBBLE = $84\n")
            f.write("!set MC_LOG = $85\n")
            f.write("!set MC_LEAVES = $86\n")
            f.write("!set MC_PLANK = $87\n")
            f.write("!set MC_COALORE = $88\n")
            f.write("!set MC_IRONORE = $89\n")
            f.write("!set MC_SAND = $8a\n")
            f.write("!set MC_GLASS = $8b\n")
            f.write("!set MC_SAPLING = $8c\n")
            f.write("!set MC_TABLE = $8d\n")
            f.write("!set MC_FURNACE = $8e\n")
            f.write("!set MC_CHEST = $8f\n\n")
        for src in generated:
            f.write(f'!source ".build/{src.name}"\n')


def main() -> None:
    strip_old_build_dir()
    all_sources = []
    for src in BLOCKS64K_SOURCES + KICK3D_SOURCES:
        if src not in all_sources:
            all_sources.append(src)
    generated_by_source = {src: normalize_source(src) for src in all_sources}

    write_entrypoint(
        "blocks64k_kick3d_acme.asm",
        [generated_by_source[src] for src in BLOCKS64K_SOURCES],
        include_blocks64k_constants=True,
    )
    write_entrypoint(
        "kick3d_acme.asm",
        [generated_by_source[src] for src in KICK3D_SOURCES],
        include_blocks64k_constants=False,
    )


if __name__ == "__main__":
    main()
